name: Check Version Bump

on:
  pull_request:
    branches: [main]

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR branch version
        run: |
          VERSION_PR=$(jq -r .version package.json)
          echo "VERSION_PR=$VERSION_PR" >> $GITHUB_ENV

      - name: Get base branch version
        run: |
          git fetch origin main
          git checkout origin/main -- package.json
          VERSION_MAIN=$(jq -r .version package.json)
          echo "VERSION_MAIN=$VERSION_MAIN" >> $GITHUB_ENV
          git checkout HEAD -- package.json

      - name: Compare versions
        run: |
          if [ "$VERSION_MAIN" == "$VERSION_PR" ]; then
            echo "Version has not been updated in package.json"
            exit 1
          else
            echo "Version has been updated: $VERSION_MAIN -> $VERSION_PR"
          fi
